command: [
  "streamlit", 
  "run",
  "home.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: "SERVING_ENDPOINT"
    valueFrom: "serving-endpoint"
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"
  - name: "GENIE_SPACE_ID"
    valueFrom: "genie-space"
  - name: "KBKA_SERVING_ENDPOINT"
    valueFrom: "kbka-serving-endpoint"
  - name: "STKA_SERVING_ENDPOINT"
    valueFrom: "stka-serving-endpoint"